### ISSUE TITLE
Ability to pass validatorOptions to yup

### ISSUE THREAD

**Issue by clarkey** [mckacz/yup-env#5]
First of all, thank you for creating this library. Would you consider implementing a way to pass `validatorOptions` down to yup so I can configure things like `abortEarly` so the `ValidationError` contains all errors, instead of only the first one?

Perhaps something like this?

```js
const appConfig = yupEnv({
  schema,
  env: env.parsed,
  prefix: "APP_",
  levelSeparator: "__",
}, {
    abortEarly: false,
    strict: true
});
```

**Comment by mckacz** [comment]
Good idea! Definitely a useful option. I'll implement and publish it in the next few days.

**Comment by mckacz** [comment]
Hi again, I've just published a new release with the feature. You can pass options to yup this way:

```typescript
const appConfig = yupEnv({
  schema,
  env: env.parsed,
  prefix: "APP_",
  levelSeparator: "__",
  validate: {
    abortEarly: false,
    strict: true
  }
});
```
